-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versi server:                 5.7.33 - MySQL Community Server (GPL)
-- OS Server:                    Win64
-- HeidiSQL Versi:               11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Membuang struktur basisdata untuk my_blog
CREATE DATABASE IF NOT EXISTS `my_blog` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `my_blog`;

-- membuang struktur untuk table my_blog.categories
CREATE TABLE IF NOT EXISTS `categories` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `categories_name_unique` (`name`),
  UNIQUE KEY `categories_slug_unique` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Membuang data untuk tabel my_blog.categories: ~3 rows (lebih kurang)
/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
INSERT IGNORE INTO `categories` (`id`, `name`, `slug`, `created_at`, `updated_at`) VALUES
	(1, 'Web Programming', 'web-programming', '2021-10-25 03:37:15', '2021-10-25 03:37:15'),
	(2, 'Web Design', 'web-design', '2021-10-25 03:37:15', '2021-10-25 03:37:15'),
	(3, 'Personal', 'personal', '2021-10-25 03:37:15', '2021-10-25 03:37:15');
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;

-- membuang struktur untuk table my_blog.failed_jobs
CREATE TABLE IF NOT EXISTS `failed_jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Membuang data untuk tabel my_blog.failed_jobs: ~0 rows (lebih kurang)
/*!40000 ALTER TABLE `failed_jobs` DISABLE KEYS */;
/*!40000 ALTER TABLE `failed_jobs` ENABLE KEYS */;

-- membuang struktur untuk table my_blog.migrations
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Membuang data untuk tabel my_blog.migrations: ~9 rows (lebih kurang)
/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;
INSERT IGNORE INTO `migrations` (`id`, `migration`, `batch`) VALUES
	(1, '2014_10_12_000000_create_users_table', 1),
	(2, '2014_10_12_100000_create_password_resets_table', 1),
	(3, '2019_08_19_000000_create_failed_jobs_table', 1),
	(4, '2019_12_14_000001_create_personal_access_tokens_table', 1),
	(5, '2021_10_16_100329_create_posts_table', 1),
	(6, '2021_10_16_110852_create_categories_table', 1),
	(7, '2021_10_25_080038_add_is_admin_to_users_table', 2),
	(8, '2021_10_27_195249_add_like_to_posts_table', 3),
	(9, '2021_10_27_231110_add_like_to_posts_table', 4);
/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;

-- membuang struktur untuk table my_blog.password_resets
CREATE TABLE IF NOT EXISTS `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Membuang data untuk tabel my_blog.password_resets: ~0 rows (lebih kurang)
/*!40000 ALTER TABLE `password_resets` DISABLE KEYS */;
/*!40000 ALTER TABLE `password_resets` ENABLE KEYS */;

-- membuang struktur untuk table my_blog.personal_access_tokens
CREATE TABLE IF NOT EXISTS `personal_access_tokens` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Membuang data untuk tabel my_blog.personal_access_tokens: ~0 rows (lebih kurang)
/*!40000 ALTER TABLE `personal_access_tokens` DISABLE KEYS */;
/*!40000 ALTER TABLE `personal_access_tokens` ENABLE KEYS */;

-- membuang struktur untuk table my_blog.posts
CREATE TABLE IF NOT EXISTS `posts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `category_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `published_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `like` bigint(20) unsigned NOT NULL DEFAULT '0',
  `dislike` bigint(20) unsigned NOT NULL DEFAULT '0',
  `comment` text COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `posts_slug_unique` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Membuang data untuk tabel my_blog.posts: ~19 rows (lebih kurang)
/*!40000 ALTER TABLE `posts` DISABLE KEYS */;
INSERT IGNORE INTO `posts` (`id`, `category_id`, `user_id`, `title`, `slug`, `image`, `excerpt`, `body`, `published_at`, `created_at`, `updated_at`, `like`, `dislike`, `comment`) VALUES
	(1, 1, 1, 'Impedit officiis aliquid consequatur nisi.', 'magni-perferendis-ut-natus-commodi', NULL, 'Ipsam assumenda ipsa quia aspernatur vel consequatur et. Ut et sint aut et omnis omnis quo. Modi rerum occaecati excepturi est molestiae.', '<p>Laboriosam error pariatur sit ea. Voluptatem laboriosam ullam tempora itaque necessitatibus. Veniam qui dicta fugiat ipsam.</p><p>Excepturi provident beatae sunt aliquam omnis facilis. Dicta excepturi sed dolorem voluptatum maxime quam in vel. Voluptatum tempore provident aperiam repudiandae placeat cumque quia doloribus.</p><p>Voluptates aliquam ratione aut aliquam sed dolore a. Tempora enim labore qui ea et. Commodi tenetur in nisi sit fugiat omnis perspiciatis. Maxime quibusdam natus aut quod et sed quod.</p><p>Tempore quos voluptatibus beatae quis cum minima. Quod nesciunt cum distinctio eum occaecati. Et laborum officiis dicta fuga.</p><p>Consectetur eligendi quia quae. Dolores voluptas quam tenetur hic aut soluta. Qui eveniet porro reprehenderit eveniet sequi. Quidem tenetur sit fugiat quo reprehenderit et enim.</p><p>Harum id non sed quia ut vero velit. Autem ut ad quo ut voluptatem dolores nihil. Aut cupiditate aut laboriosam suscipit velit.</p><p>Facere sit perspiciatis temporibus. Sunt incidunt corrupti soluta nobis. Vel qui hic quae a. Et qui est rem illum reprehenderit.</p><p>Ut incidunt aut iure. Esse molestiae est quos fugit enim reprehenderit harum. Saepe autem et facere rerum accusamus ipsa dolorem.</p><p>Ad quia cupiditate rerum quae. Vitae fuga consequatur reprehenderit eos molestias. Itaque quae est sunt aliquid enim reiciendis. Id omnis sequi non voluptatum est dolor. Itaque possimus at sint officia non consequuntur.</p><p>Quo et inventore voluptatibus quidem veritatis quo nostrum. Corporis est explicabo omnis cum corrupti nobis. Sit voluptas quia rerum aut nihil quam. Placeat sapiente sit aut cum non praesentium in aut.</p>', NULL, '2021-10-25 03:37:16', '2021-10-25 03:37:16', 0, 0, ''),
	(2, 1, 2, 'Assumenda earum consectetur.', 'ut-dolor-vel-laudantium-omnis-fugit', 'assets/post-images/J4vfHj5T5L5BOmwCyOwKz5k9Tc0qnGRNdSm8eb4U.jpg', 'Dignissimos eum molestias perferendis sed. Eaque sint facere corporis quos corporis. Sed ea quos aut sit laborum.Ut ullam qui voluptatibus modi architecto quasi ut. Id rerum est dignissimos ut omnis....', '<div>Dignissimos eum molestias perferendis sed. Eaque sint facere corporis quos corporis. Sed ea quos aut sit laborum.<br><br></div><div>Ut ullam qui voluptatibus modi architecto quasi ut. Id rerum est dignissimos ut omnis. Voluptas cumque voluptatem error doloribus inventore saepe aliquam. Pariatur consectetur qui ratione quae et repellat impedit.<br><br></div><div>Aut at qui quo incidunt eum rerum aut error. Quo quis quidem odit et. Nemo corporis sed et explicabo dolores.<br><br></div><div>Neque quaerat distinctio aspernatur. Tempora qui asperiores quaerat rem iste cupiditate est. Sit minima veritatis alias incidunt maiores animi ea. Quibusdam qui nobis quia at vero pariatur et in.<br><br></div><div>Dolores eos tempore harum. Vel pariatur sequi qui deserunt qui. Consequatur voluptatum consequuntur eos adipisci debitis officiis sit laboriosam.<br><br></div><div>Fugit dolores et doloribus atque beatae. Qui sequi voluptas libero aperiam minus quo repudiandae. Aut nam qui ad ipsum velit ut. Sit fugit nihil molestiae adipisci consequuntur sapiente.<br><br></div>', NULL, '2021-10-25 03:37:16', '2021-10-25 08:32:21', 0, 0, ''),
	(3, 2, 1, 'Labore autem labore voluptatum repudiandae nisi.', 'provident-consequatur-animi-velit-provident-vitae-dolorem-est', NULL, 'Vel illo dicta ab vel nesciunt reprehenderit sint. Quibusdam consequatur blanditiis ratione. Quae iusto rerum ut necessitatibus dolorem. Possimus qui a odit.', '<p>Adipisci nihil omnis provident est. Ipsa sit voluptas corporis exercitationem. Rem est eum rerum qui inventore. Et cumque in omnis architecto provident cumque qui dolorem.</p><p>Et eum nulla facilis autem. Quis voluptatem accusantium qui cumque temporibus. Est officia fugiat at magni. Nemo commodi corrupti soluta voluptate totam sunt deleniti.</p><p>Nihil in perspiciatis enim distinctio. Quasi ut consequatur totam et sint. Aut quas soluta sint consequatur omnis aut.</p><p>Ullam occaecati illum illo sapiente cum. Provident cumque facere amet vel autem. Qui sit est deleniti quod ipsum quisquam.</p><p>Voluptatem ab quasi consequatur dolore. Delectus sit et aliquam repellendus et. Corrupti non debitis temporibus. Earum quam illo voluptas est enim id consectetur. Atque distinctio ipsa nulla amet non.</p><p>Modi porro natus quia nisi. Ut eaque laboriosam voluptatibus est voluptatem atque vel quasi. Praesentium odio commodi eveniet illum sed aut.</p><p>Repellendus voluptatum sunt molestiae et modi non. Officia accusantium et et veniam quia laudantium. Qui illo quo harum.</p><p>Velit vero est vel quisquam voluptatem. Exercitationem rerum quidem illum soluta nemo neque molestias est. Ipsum consequuntur quia beatae ratione. Consectetur sit amet veritatis sit dignissimos ut.</p><p>Neque veniam autem voluptatum natus adipisci facilis et. Ea et aut expedita voluptates recusandae labore. In consectetur amet accusamus vero consequuntur et quae laboriosam. Voluptatem molestiae necessitatibus pariatur dignissimos tempore quos autem exercitationem.</p><p>Quos quis amet nemo amet itaque. Alias eos consequatur laboriosam distinctio libero. Nesciunt quis qui optio est illum.</p>', NULL, '2021-10-25 03:37:16', '2021-10-25 03:37:16', 0, 0, ''),
	(4, 2, 1, 'Odit doloremque est.', 'atque-est-optio-perspiciatis-omnis-officiis', NULL, 'Molestiae maiores dolores et omnis tempore quia. Aut qui tempore tempore voluptatem voluptatem illum impedit. Quas rem explicabo et voluptatem repellendus alias placeat. Aspernatur in et et rerum.', '<p>Sunt omnis omnis natus sed unde eos. Incidunt corrupti quisquam ad at. Alias aliquid explicabo et iure eos.</p><p>Natus consequatur fugit blanditiis. Qui facilis ullam optio laborum dolores atque voluptas voluptatum. Est deserunt omnis omnis quisquam ipsa saepe.</p><p>Vel blanditiis rerum vel fugit. Enim provident quia deserunt aut debitis. Maiores sed ea facere in pariatur et.</p><p>Quibusdam quo nulla perferendis rem. Illo sunt eveniet excepturi id qui sed. Quod labore et iure ipsa ut. Nam dolorem nemo sunt in animi.</p><p>A quis voluptatem earum in molestias est recusandae. Quas ab est dicta eaque enim omnis modi incidunt. Illum modi qui rerum iusto vero omnis incidunt. Nihil ipsa impedit illo officia at sint.</p><p>Placeat et est aut exercitationem. Dolores odio qui molestias blanditiis. Ut id accusantium ut voluptatem. Sed omnis eaque recusandae quo voluptates.</p><p>Incidunt consequatur provident vitae laboriosam esse quibusdam maiores. Qui a harum voluptatibus sequi perferendis quibusdam molestiae. Quia magni sit minus officia.</p><p>Repellendus voluptas est officia harum alias aspernatur. Enim magni itaque corporis fugiat eius alias fugiat.</p><p>Quo voluptatum dolor fugiat est ea eveniet blanditiis. Occaecati voluptas sunt ut. Nulla error quod commodi.</p><p>Accusantium amet aperiam alias sit quo minima. Voluptatem rerum saepe aliquid magni rerum enim quasi. Et sunt numquam qui et cumque et. Aut incidunt debitis ad.</p>', NULL, '2021-10-25 03:37:16', '2021-10-25 03:37:16', 0, 0, ''),
	(5, 2, 3, 'Aut ut consequatur eligendi quas ea et.', 'magni-sint-explicabo-voluptas-suscipit-rerum-autem', NULL, 'Ipsum nulla laboriosam rerum. Dolorem eius omnis necessitatibus praesentium rerum velit. Voluptatem hic dignissimos ratione et possimus libero rerum ut. Ut voluptates eum consequatur delectus laboriosam quia.', '<p>Maxime dicta at sit sed ut repellendus et neque. Qui deleniti quaerat consequuntur praesentium. Itaque quam sint natus est incidunt ab est ullam. Quia fugiat quidem possimus provident delectus deserunt accusantium est.</p><p>Non et veritatis tempora ipsum repellendus. Quo accusantium nobis modi quo ut aut. Facilis est aspernatur rerum ratione ea saepe.</p><p>Et facere omnis quia consequatur eum perferendis. Nemo perspiciatis non dolor dolorum quia. Ratione omnis voluptas molestiae fugiat ducimus. Maiores aperiam qui quibusdam.</p><p>Omnis quos et repellendus. Eveniet incidunt ad quia ducimus voluptatem et. Officiis consequatur aliquid iusto iure ducimus.</p><p>Eaque iusto architecto doloribus enim. Dolor ducimus quia commodi tempora consequuntur quibusdam. Quas sed architecto sunt occaecati.</p><p>Quas vel aut dolor enim ab maxime voluptatem repellendus. Et et voluptates facilis sit optio velit aperiam. Sit dignissimos magni doloribus veritatis mollitia quo sit.</p><p>Minima laudantium ea dolores quis vero dicta. Nihil sit ut molestiae qui officiis excepturi. Quia accusamus rerum non excepturi enim ea non. Eos ea id veritatis mollitia qui dolor laborum qui.</p><p>Porro possimus quia sed suscipit quam eum. Sint impedit in nihil id enim. Temporibus velit tenetur illum voluptatum quia vel similique. Fuga autem facere et voluptate rerum ab consequatur consequatur.</p>', NULL, '2021-10-25 03:37:16', '2021-10-25 03:37:16', 0, 0, ''),
	(6, 2, 3, 'Qui sed.', 'voluptatibus-in-vel-harum-exercitationem-reprehenderit-aut', NULL, 'Commodi praesentium vero minus itaque nemo. Tempora laborum voluptatem nobis molestiae est. Nobis aut non ad velit dolorem. Repudiandae ducimus labore praesentium quo neque non possimus.', '<p>Dolores ea nihil sit repellendus et. Qui aut non eligendi sunt quas. In et et ratione vitae nesciunt beatae. Ut ullam id adipisci autem.</p><p>Quod veritatis nemo dolores assumenda labore autem. Ex rerum quia perspiciatis itaque vel est velit. Dolor accusantium incidunt qui non sunt repellat. Enim animi eos ullam a eos tenetur esse.</p><p>Vel alias quisquam ab quibusdam voluptatum ipsum tempore rerum. Quidem reiciendis totam temporibus occaecati nihil in odio. Aut beatae ex molestiae omnis placeat voluptas. Dolorum neque quo velit et provident.</p><p>Nulla quia quos neque eaque beatae. Et veritatis dolor odit libero qui laudantium. Sed totam eligendi deserunt quis possimus. Nostrum qui excepturi impedit quia.</p><p>Dolor eos est distinctio dolorem fugiat distinctio. Et voluptate sit ut nulla ut. Suscipit reiciendis veritatis nesciunt iure eum tenetur adipisci.</p><p>Sunt autem necessitatibus quaerat placeat perspiciatis at. Fugit non odio fugit similique eum. Dolor inventore iste repellendus impedit enim sed quam. Provident vero officia aperiam et.</p><p>Nulla et placeat eum praesentium et. Molestiae rerum omnis officiis architecto repellat non voluptatem. Natus et velit cumque cumque dolores quia ab. Sint non perspiciatis autem sint in.</p><p>Eligendi odit eum ea inventore totam architecto cumque doloribus. Vitae iusto fugit qui voluptates excepturi praesentium sit. Eius illum pariatur officia quo quisquam quisquam.</p><p>Reprehenderit cupiditate veritatis libero libero tempore. Et eius dolore non quo deleniti occaecati. Itaque sunt id et nisi.</p>', NULL, '2021-10-25 03:37:16', '2021-10-25 03:37:16', 0, 0, ''),
	(7, 1, 2, 'Et nam aut fugit consequatur et aut incidunt.', 'quod-amet-exercitationem-ut-adipisci', 'assets/post-images/JT4j8dgx5zFljePJsLkE0rpd4mjO3fb8aUfoofqE.jpg', 'Dolores sit aut ut sunt nesciunt. Minus ea aut suscipit velit repellendus dolor iste. Autem ullam consequatur hic aut suscipit. Qui accusamus dignissimos aut quisquam excepturi esse veritatis.Quis ass...', '<div>Dolores sit aut ut sunt nesciunt. Minus ea aut suscipit velit repellendus dolor iste. Autem ullam consequatur hic aut suscipit. Qui accusamus dignissimos aut quisquam excepturi esse veritatis.<br><br></div><div>Quis assumenda inventore qui temporibus. Quia molestias corrupti nesciunt rerum.<br><br></div><div>Doloribus quod aut delectus necessitatibus placeat. Similique ab aut odit non harum soluta mollitia. Doloremque accusantium et dolorem quae nostrum expedita quis. Provident enim sapiente praesentium porro consequatur doloribus.<br><br></div><div>Eveniet aut officia voluptatibus aut fugit voluptatem. Quia aspernatur ipsa possimus. Sint voluptatum qui saepe quisquam quia. Sit possimus sit mollitia debitis.<br><br></div><div>Assumenda perspiciatis corrupti rerum aut est. Facilis recusandae tempore quidem suscipit est. Laudantium reprehenderit laboriosam non architecto molestiae consequatur. Aperiam nesciunt nihil autem ipsum esse eum. Et tempore debitis minus praesentium.<br><br></div>', NULL, '2021-10-25 03:37:16', '2021-10-25 08:35:15', 0, 0, ''),
	(8, 2, 3, 'Magni accusamus sed velit.', 'enim-autem-neque-mollitia-molestiae-sed-aliquid-dicta', NULL, 'Odit omnis consequatur enim voluptatem et quasi rerum neque. Non molestiae voluptatum voluptates mollitia. Ut laudantium et itaque temporibus suscipit quo ad. Earum eum et quis voluptatibus animi qui.', '<p>Suscipit distinctio possimus consectetur dolorum est. Eligendi sint tenetur quae facilis nihil facilis. Deserunt accusamus quibusdam ut molestias omnis omnis incidunt.</p><p>Voluptatem doloremque tenetur fugit dolores corrupti. Reprehenderit et et et et nihil. Molestias odio non placeat fugiat voluptatem.</p><p>Vero vitae consequatur odio incidunt quae natus architecto. Natus ea fugit fuga cum quia minima.</p><p>Est quod rerum id facilis quaerat fugit vitae modi. Illo qui nemo vero sit. Repudiandae odio ut vero aut qui beatae voluptas est. Beatae voluptas ut et est nesciunt.</p><p>Sed deleniti veritatis minima. Enim est nesciunt sint tempore dolore. Officia maxime beatae voluptatem quia non distinctio. In temporibus neque quia qui laboriosam adipisci vero.</p>', NULL, '2021-10-25 03:37:16', '2021-10-25 03:37:16', 0, 0, ''),
	(9, 2, 2, 'Commodi suscipit eveniet hic veniam enim corporis amet.', 'quasi-est-vel-velit-ullam-alias-dolor-rerum', NULL, 'Et esse sed quae at aperiam vitae at. Esse dicta temporibus ab asperiores non vel tempore. Dolor ut eius voluptates nihil facilis rerum voluptatibus. Consequatur sint exercitationem adipisci autem quia modi ad. Illo quis provident minima sed qui corporis.', '<p>Magnam ut praesentium commodi dolores consequatur est aut repudiandae. Ipsum placeat nulla et voluptatem nobis qui. Molestiae dolores nihil ea ut suscipit repellat.</p><p>Vel culpa omnis ducimus quia fuga. Neque aut quas nobis tempore quia.</p><p>Harum esse at laudantium est corporis. Deleniti ratione voluptas excepturi repudiandae expedita ad dolores error. Rerum totam nihil perferendis tempora eligendi. Minima odit qui esse omnis numquam. Tenetur alias ut optio molestias tempora vel.</p><p>Et cupiditate non nam aut delectus ullam enim illo. Quo molestiae iure deleniti eos praesentium. Harum voluptas autem ut dolor sint voluptatibus necessitatibus. Animi quia aut provident et quos.</p><p>Adipisci commodi voluptatem reiciendis alias molestias quo. Quod sed sapiente rerum facere. Ut sed maxime sint sint autem. Voluptatibus sunt at recusandae esse vel corporis.</p><p>Aliquam magni aut sit corrupti. Adipisci ut voluptatum ducimus nisi et fuga. Iusto non ut animi quisquam praesentium ducimus. Qui aut modi aperiam ipsam perferendis quisquam aut provident. Ipsa sed omnis aliquam quis est necessitatibus aut.</p><p>Qui voluptas ut reprehenderit vitae consequatur non a alias. Odit dolorem vel natus. Optio accusamus fugiat fugit dicta voluptatem. Voluptate laborum est rerum. Quae cumque sunt ad sint itaque nulla dolores.</p><p>Veritatis sit dicta dolores aut porro exercitationem maxime. Odio libero possimus et blanditiis eaque qui. Earum in ut omnis voluptatem et voluptatem. Voluptatum perspiciatis earum nostrum mollitia velit consequatur corporis beatae.</p>', NULL, '2021-10-25 03:37:16', '2021-10-25 03:37:16', 0, 0, ''),
	(11, 2, 3, 'Iusto sint.', 'dolorem-beatae-consequatur-sequi-quo-ut-alias-ab', NULL, 'Quod repudiandae eaque facilis perspiciatis est. Quidem optio esse ipsa quo voluptates voluptatem. Quasi unde doloribus tempore ducimus. Dolorem amet rerum doloremque at soluta.', '<p>Maxime aut quas vero sunt quis cum. Ab repellat at harum veritatis praesentium qui. Est voluptas sapiente numquam animi. Laborum quas ut consectetur.</p><p>Alias tempore velit sed repellendus blanditiis est. Pariatur laudantium praesentium eos ab laudantium explicabo labore aliquam. Molestias fuga aut ullam. Quia expedita itaque quod quae qui rem aliquid.</p><p>Et et est esse ut ducimus. Quibusdam repellat dolor dolor aperiam consequatur ratione atque. Numquam reprehenderit est aut harum.</p><p>Doloribus nesciunt eius a ipsa excepturi inventore qui nobis. Sed veniam nisi modi quasi eligendi ipsum inventore.</p><p>Dolorum minus ut quo repellat. Quas voluptatem quia rerum dolorem. Saepe veritatis libero ullam deserunt error.</p><p>Sint distinctio iusto at nihil nisi. Similique eos accusamus neque doloribus aliquid. Maiores cum deserunt repellendus enim laborum unde molestias voluptatem. Et rerum laboriosam sit corporis.</p><p>Maxime fugit sint odio omnis nisi. Sit harum laboriosam distinctio magnam tempora.</p><p>Architecto distinctio amet quis magnam ut. Id blanditiis doloremque eum qui id. Repellat sunt aut consequuntur hic in necessitatibus non. Dignissimos vel quae a sunt.</p><p>Delectus ut dolores sit animi minima deleniti ut. Voluptatibus dolorum laboriosam odit. Iure hic est libero. Nihil placeat ea quibusdam quis.</p><p>In pariatur unde tenetur est officia soluta. Qui dignissimos placeat repellat ipsum qui et temporibus sint. Consectetur eveniet asperiores in voluptas qui animi.</p>', NULL, '2021-10-25 03:37:16', '2021-10-25 03:37:16', 0, 0, ''),
	(12, 2, 3, 'Ratione ipsam labore incidunt dolorum et.', 'quis-eveniet-aut-dignissimos-veniam-asperiores', NULL, 'Dolores et ut non consequatur dolorem. Rerum rem consequatur incidunt cupiditate perferendis. Cupiditate rem minima dolores eum.', '<p>Eveniet et voluptas et vel. Enim alias ut veritatis adipisci. Id et placeat sapiente impedit officia.</p><p>Ad nobis hic exercitationem blanditiis omnis impedit. Quas quia consectetur accusantium quia rerum ducimus. Aperiam totam expedita tempora quia.</p><p>Dolor nulla vero laboriosam cupiditate laboriosam ratione cumque minima. Libero voluptas magni rerum omnis recusandae qui. Recusandae rerum et aut id repudiandae aut.</p><p>Neque consequuntur atque nihil iste error suscipit. Atque accusantium non quam voluptate fugiat numquam ut quia. Odio harum dignissimos voluptas in a accusantium.</p><p>Necessitatibus est ullam eius omnis voluptatem. Asperiores excepturi officia nostrum unde quia voluptas possimus. Et sunt sint itaque et ut. Nemo suscipit omnis harum.</p><p>Vero error et et repellendus cupiditate vel. Sed est quam voluptatem facere autem. Tenetur dolores mollitia sed et aut.</p><p>Officiis voluptas architecto sunt. Natus numquam aliquid in non.</p><p>Ut rerum veritatis esse consectetur facilis veritatis facere. Numquam nemo non est magnam facere perspiciatis non. Et nostrum dolores eveniet quis error tenetur fugit possimus. Nihil et quia et ut repudiandae praesentium.</p><p>Amet nam non sint tempore. Aut mollitia beatae illum vel. Quae enim nesciunt dolor ipsa repudiandae. Ut consectetur magnam incidunt officia ut excepturi ea suscipit.</p>', NULL, '2021-10-25 03:37:16', '2021-10-25 03:37:16', 0, 0, ''),
	(13, 1, 3, 'Sed dicta.', 'vero-inventore-quo-modi-ut-minima', NULL, 'Eos consequuntur doloribus qui sunt. Cum voluptates ad sit laborum reiciendis. Aliquam ad natus dolorum et est dolore.', '<p>Voluptas non labore corporis labore. Inventore non distinctio sunt qui ea ad dolores.</p><p>Cupiditate itaque voluptatem amet ut et eos. Quia numquam aliquam deserunt repellat eos tempore. Placeat eligendi aspernatur rerum consectetur.</p><p>Nesciunt accusamus fugit recusandae qui autem et et. Iste quam quis tempora dicta aut. Et est voluptas aut a ad dolor.</p><p>Repellat et delectus adipisci odit. Ut aperiam deserunt voluptatibus voluptates accusantium. Pariatur omnis architecto reprehenderit repellendus saepe vero.</p><p>Non illo et et modi enim non. Dicta sed quod architecto nobis mollitia excepturi. Aut eos dolorum possimus accusamus.</p><p>Optio qui velit nesciunt et fuga quas quam. Aut impedit voluptatibus ea illum. Et sed commodi eum nisi corporis voluptate blanditiis. Perspiciatis eos quia eos dolor velit.</p><p>Nobis quisquam nihil et quibusdam molestias quia qui suscipit. Asperiores et fugiat officia velit. Et asperiores eum non laboriosam consequuntur impedit quo. Ratione nihil sed atque ipsum nulla vel quia.</p><p>Perferendis velit quia tempore sint quia. Animi a magnam voluptatum autem consequatur ad. Dignissimos aut voluptatem dolor doloremque atque et.</p><p>Illo sit sunt quam sapiente consectetur id praesentium enim. Illum quia temporibus minima sapiente architecto aut quia. Quam qui est voluptas.</p><p>Ut reprehenderit qui nemo cumque quia voluptates. Occaecati delectus dolores ut. Sed libero iure maxime nostrum. Officiis fuga accusantium et.</p>', NULL, '2021-10-25 03:37:16', '2021-10-25 03:37:16', 0, 0, ''),
	(14, 1, 2, 'Ut asperiores doloremque voluptas mollitia natus sunt voluptatum et eius.', 'velit-voluptates-autem-asperiores-maxime-voluptas-delectus-enim', NULL, 'Consequatur occaecati ratione similique sit. Non beatae consequatur sed reprehenderit quis. Molestiae beatae voluptas hic est voluptas aut.', '<p>Nisi molestiae suscipit distinctio nulla ipsa soluta officiis explicabo. Possimus voluptatem quia quas dicta iure. Vitae voluptatem voluptas sit qui rerum.</p><p>Ipsam alias odio quod vel. Eius est aliquam quia et assumenda quia. Quis laudantium ut sequi itaque consequatur in suscipit. Vel vitae sapiente temporibus ab.</p><p>Dolorem deserunt eius in. Amet id dolor eius sapiente sint voluptatum facilis labore. Iste sint quia aut ut asperiores temporibus corporis. Molestiae nesciunt culpa minima voluptas enim iusto.</p><p>Et est ut nemo modi cupiditate. Aliquam sapiente enim molestiae pariatur doloremque dolorum culpa. Eos maxime veniam asperiores dolore aut illo nihil doloribus.</p><p>Aut voluptatem deserunt voluptas commodi necessitatibus. Dolorem dolorum magni aliquam odio. Aut sed facere ex. Dolores sequi illo aut velit.</p><p>Nisi quia ut eligendi eveniet quisquam accusamus cumque. Consequatur natus veniam enim molestiae est. Quo doloremque tenetur ipsum incidunt.</p><p>Quod voluptatem consequuntur sit debitis vero. Odit ea eveniet cupiditate minima.</p><p>Omnis assumenda molestiae reiciendis quam ab. Sit porro aspernatur nobis ut inventore eaque itaque sapiente. Animi rerum iusto corporis eos dolorem. Illo eaque ipsam vel neque quam et.</p><p>Omnis vel totam deleniti id quia id. Et quia natus hic sit sunt et. Amet debitis nihil dolore dolorem. Illum vel explicabo occaecati quo iusto quia non.</p>', NULL, '2021-10-25 03:37:16', '2021-10-25 03:37:16', 0, 0, ''),
	(15, 1, 2, 'Quibusdam vel consequatur id dignissimos provident quia repellat sunt corporis eos.', 'id-quos-et-et-aspernatur-qui', NULL, 'Fugiat iusto alias aut dolores voluptatibus quae ex sit. Laudantium fuga soluta sit ipsa. Inventore sed dolorem id quos. Ratione qui perferendis ut totam molestias ipsa tenetur.', '<p>Eos rerum itaque corporis fuga at natus. Atque enim laudantium ut sit quis doloribus dolor. Doloremque nemo tempora temporibus id. Enim voluptas suscipit perspiciatis autem quod dolorem veniam.</p><p>Et laboriosam et enim non dolorem. Explicabo fugit repellendus ipsam asperiores dolorem est sed. Aut et et enim culpa facilis sed. Aut occaecati ut voluptatem vero aut.</p><p>Autem necessitatibus commodi repellat sed iste placeat doloremque. Temporibus a consequatur facere eum neque. Aliquam quae rerum incidunt. Adipisci consequuntur consequatur corrupti aut.</p><p>Sit reprehenderit velit expedita. Unde accusantium sapiente doloribus inventore rerum iure qui quae. Omnis dolorem inventore incidunt harum corrupti fugiat dolor.</p><p>Blanditiis id magni est voluptas ex laboriosam. Nisi ipsa sunt eius dolor similique ex eos. Voluptas tempora aspernatur corrupti aut explicabo. Voluptatem et at aut voluptas ut deserunt ad voluptates.</p><p>Minus eaque voluptatem eveniet voluptates. Qui voluptatem dolorum eius placeat fugiat nobis aut. Aliquam similique omnis id sint. Voluptatem sint et earum quasi dolor consectetur et minima.</p><p>Alias ducimus esse est ea. Reiciendis rerum enim accusamus voluptatem asperiores rerum. Ducimus ut sed officia vitae natus.</p>', NULL, '2021-10-25 03:37:17', '2021-10-25 03:37:17', 0, 0, ''),
	(16, 1, 3, 'Dolorem temporibus magni voluptatem sit.', 'dolore-quos-dolor-beatae-et', NULL, 'Mollitia rerum accusantium recusandae enim. Esse aut aut cumque. Iure quasi dolorem modi nisi.', '<p>Enim error cum modi repellat et. Quaerat cum aliquid nostrum alias quidem quisquam. Facilis perspiciatis reiciendis quod ex.</p><p>Nihil necessitatibus qui iste ab est ipsam. Ratione voluptate tenetur aut aut molestias. Voluptatem temporibus neque veniam facere rerum.</p><p>Minima molestiae non non praesentium fugit nihil. Ducimus ducimus officia quos quo accusantium quod. Assumenda laudantium quo id et.</p><p>Accusantium numquam perspiciatis possimus tempora unde dolorem occaecati repellendus. Quas possimus deleniti modi perferendis veritatis accusantium culpa. Unde voluptatem ex harum sed.</p><p>Ratione exercitationem nemo non cumque facilis accusamus odio perspiciatis. Eos pariatur et aut sint dicta. Nam dolore laborum eius ipsa minus.</p><p>Dolores aliquam et rem aut aliquam quisquam. Neque doloribus magni velit doloribus vel eos. Numquam aut esse numquam dolorem maiores at ad dolorum. Voluptas temporibus consequatur impedit est est.</p><p>Accusamus reprehenderit cum assumenda beatae. Qui distinctio excepturi ut ut fugiat. Voluptas nam repudiandae nostrum.</p><p>Sint veritatis molestiae dolorum et dolore nulla ut. Dolor quidem facere sit ea quia. Omnis in dolores dolorum. Maxime hic et est eos.</p><p>Dignissimos similique quod accusamus eos consequatur voluptates fugiat. Inventore sint quaerat eum et architecto voluptas. Et velit mollitia id saepe.</p><p>Mollitia qui consequuntur aspernatur doloremque vitae. Expedita ad est cum quia et qui voluptatem. Laudantium ut quo qui repellendus facere. Dolorem cumque et rerum fuga sit.</p>', NULL, '2021-10-25 03:37:17', '2021-10-25 03:37:17', 0, 0, ''),
	(17, 2, 3, 'Quisquam ducimus officia ipsum fugit expedita mollitia pariatur.', 'et-eligendi-at-tempore-qui', NULL, 'Corrupti aut ratione unde et sint cumque recusandae eius. Voluptatum natus a corrupti eum. Sunt pariatur qui et aspernatur numquam repellat nam aut. Aut eum deleniti quibusdam mollitia.', '<p>Quo blanditiis ut eos quae sed ea voluptatem et. Praesentium placeat rerum ipsa omnis beatae sunt. Id consequatur eum quia non non nihil fugit. Quia aut et at quas est nostrum dolore.</p><p>Accusantium nostrum nobis magnam dolorem aut. Soluta consequatur quasi occaecati fugiat necessitatibus. Accusamus qui nulla quod officia ut quis.</p><p>Quaerat nobis nemo porro dolores fuga tempora in. Vel nobis eius ex.</p><p>Id eius sit doloremque non quisquam magnam sapiente. Non ratione assumenda aliquid. Qui doloribus necessitatibus molestiae ea id et expedita.</p><p>Laboriosam modi quaerat quae quia quae. Voluptatem eveniet enim est ipsam.</p>', NULL, '2021-10-25 03:37:17', '2021-10-25 03:37:17', 0, 0, ''),
	(18, 2, 3, 'Quasi dolorem dolor.', 'blanditiis-deserunt-molestiae-qui-ut-ullam-iusto', NULL, 'Labore repudiandae fuga qui maxime. Consequuntur repudiandae magni qui ipsam perspiciatis velit odio. Rerum totam delectus quos totam consequatur qui est. Nemo amet consequatur porro quas eos doloremque quia. Minima ipsam labore voluptates adipisci.', '<p>Et veritatis at est quidem dolores dolore. Quasi quo beatae et dignissimos beatae. Ea quidem aperiam ut exercitationem fuga.</p><p>Magni ratione quo omnis laudantium aut. Officia quo nesciunt tempora. Sint porro iste modi quasi. Illum excepturi vitae sint labore est.</p><p>Voluptatem labore deserunt eaque earum eos non neque. Omnis ea aut veritatis est.</p><p>Id facere reprehenderit esse quae nam. Rem et eius sed enim. Consequatur magnam molestias incidunt qui. Ut veniam quam recusandae possimus consequatur est.</p><p>Aliquid accusamus maxime laudantium est rerum in voluptatum. Eaque ut voluptatem vel sint debitis nihil. Eos accusantium occaecati consequatur. Itaque minus cum modi. Aut at magnam id pariatur.</p><p>Dolorum id voluptates est. Sed quidem neque et omnis aliquid qui.</p><p>Aut sed facilis molestias corporis itaque corporis ea. Nesciunt modi pariatur et. Inventore velit beatae excepturi molestiae eos maiores rerum.</p><p>Nostrum ea voluptatem possimus accusamus. Molestiae quo autem vel error aut ratione. Nihil vitae tempora hic expedita odio quae magnam. Et mollitia est alias et.</p><p>At quas et hic facilis. Velit deserunt voluptatem assumenda eos iusto sed doloremque. Nesciunt adipisci est mollitia excepturi minima unde. Est sit vel ut et vel aut.</p><p>Libero velit perferendis voluptatum asperiores. Qui quod laborum est quasi deserunt dicta velit et. Quasi architecto quaerat quis vel similique aut quia. Sint eum voluptatem ipsam quod qui.</p>', NULL, '2021-10-25 03:37:17', '2021-10-25 03:37:17', 0, 0, ''),
	(19, 2, 3, 'Aut necessitatibus ut qui.', 'ad-ut-rerum-et-molestiae-repudiandae', NULL, 'Ut corporis molestiae sint reprehenderit et voluptate iure qui. Quia optio rerum iure ab hic sed. Eos corporis dolores quaerat voluptatem. Non at iusto ut ratione nemo dignissimos.', '<p>Dignissimos cumque modi excepturi enim dolores quaerat. Cumque vero voluptatem pariatur laboriosam. Fugiat reprehenderit nemo qui animi et architecto.</p><p>Qui id vero consequuntur. Molestias exercitationem sed adipisci explicabo. Ut tempora rerum recusandae praesentium.</p><p>Laboriosam repellat porro voluptatem aut maiores a consequatur. Aspernatur quis impedit animi sint quis placeat. Inventore consequuntur accusamus optio dolor.</p><p>Blanditiis necessitatibus aperiam iure quia. Quia repudiandae esse voluptates dolor sed voluptatem temporibus. Quo animi sunt deserunt blanditiis. Modi est rem dolor quis quisquam.</p><p>Similique molestiae rem optio vel ut iure suscipit laboriosam. Ratione at qui iusto est pariatur. Accusamus recusandae adipisci nihil perspiciatis. Explicabo et iure neque sed nulla molestias et.</p>', NULL, '2021-10-25 03:37:18', '2021-10-25 03:37:18', 0, 0, ''),
	(20, 2, 2, 'Voluptas occaecati beatae.', 'dignissimos-voluptatem-quisquam-non-ratione-ut-at-ut', NULL, 'Molestiae sed eveniet assumenda recusandae recusandae ut. Dolores et deleniti voluptatem.', '<p>Qui error harum officiis ab fuga. Voluptatem tenetur natus provident aspernatur dolorem odit praesentium maxime. Qui iure molestiae eius. Sed nihil suscipit id odio nemo consequatur eius voluptate.</p><p>Reiciendis aliquid voluptatem eos excepturi nobis explicabo. Quaerat molestias porro vero qui animi maiores facere. Omnis eum molestiae aut repellendus ut. Quis sit voluptas quia facilis.</p><p>Ipsum est quo dignissimos placeat alias praesentium facilis quaerat. Aperiam ratione quo dolor est reprehenderit laudantium consequatur. Eum sint sint ipsam nihil quia magnam. Id qui libero beatae quia.</p><p>Minima vel aut voluptatibus id. Dolorem quam iusto consequatur earum aut. Vel non qui eveniet fugit. Vel deserunt est cumque voluptas et quisquam nisi tempora.</p><p>Tempore excepturi illo fuga quia aut beatae. Ea veniam nihil nostrum nihil voluptatibus ratione non. Exercitationem qui velit molestiae. Velit quisquam magnam fugit dolorem nemo exercitationem.</p><p>Sit omnis qui eos ea tempora assumenda. Unde repellendus inventore quas quaerat id porro. Et delectus similique molestiae. Nihil ut vel veritatis labore nulla.</p>', NULL, '2021-10-25 03:37:18', '2021-10-25 03:37:18', 0, 0, '');
/*!40000 ALTER TABLE `posts` ENABLE KEYS */;

-- membuang struktur untuk table my_blog.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `is_admin` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_username_unique` (`username`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Membuang data untuk tabel my_blog.users: ~4 rows (lebih kurang)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT IGNORE INTO `users` (`id`, `name`, `username`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `is_admin`) VALUES
	(1, 'Shofian Al Fikri', 'shofian', 'shofian@gmail.com', NULL, '$2y$10$hpESADYsDAdnl4omxqFwIeaUTEZ0jRdqUXTUy7sjImQkpZBh.ZLB2', NULL, '2021-10-25 03:37:12', '2021-10-25 03:37:12', 1),
	(2, 'Damu Widodo', 'xanana.palastri', 'saragih.oni@example.net', '2021-10-25 03:37:15', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'LCGp8ErywvMgJRCqvJ5Q472rwGyk2miyPP4tTv2jkXA7CiooQjhQGXT9je6q', '2021-10-25 03:37:15', '2021-10-25 03:37:15', 0),
	(3, 'Rachel Namaga', 'jailani.karimah', 'karimah.uyainah@example.com', '2021-10-25 03:37:15', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'uPkRlaRdGU7dZzdCe4ULimfgvCXJ6QW2FluOziSORlAWTto4V5jRSyU2W2hH', '2021-10-25 03:37:15', '2021-10-25 03:37:15', 0),
	(4, 'Halima Fujiati S.Ked', 'sitorus.puput', 'vkuswandari@example.com', '2021-10-25 03:37:15', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Gph4fAS2sz', '2021-10-25 03:37:15', '2021-10-25 03:37:15', 0);
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
